name: Run Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Node versi 20
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Jalankan HTTP server di background
      - name: Start HTTP server
        run: npx http-server ./ -p 8080 &

      # Tunggu server siap
      - run: sleep 5

      # Jalankan Cypress
      - uses: cypress-io/github-action@v5
        with:
          start: false       # karena server sudah jalan
          wait-on: 'http://127.0.0.1:8080/index.html'
          browser: chrome
