name: Run Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code_verification:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node versi 20
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Jalankan HTTP server untuk HTML
      - name: Start HTTP Server
        run: npx http-server ./ -p 8080 &

      # 5. Tunggu server siap
      - name: Wait for server
        run: sleep 5

      # 6. Jalankan Cypress tests
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          start: false
          wait-on: 'http://127.0.0.1:8080/index.html'
          browser: chrome
