name: Run Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node versi kompatibel
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - run: npm ci

      # 4. Start HTTP server
      - name: Start HTTP server
        run: npx http-server ./ -p 8080 &

      # 5. Tunggu server siap
      - run: sleep 5

      # 6. Jalankan Cypress
      - uses: cypress-io/github-action@v5
        with:
          start: false
          wait-on: 'http://127.0.0.1:8080/index.html'
          browser: chrome
